data:extend({
    -- Startup: consumed at data stage by the nauvis map-gen takeover.
    {
        type = "int-setting",
        setting_type = "startup",
        name = "diggy-carve-out-radius",
        default_value = 12,
        minimum_value = 6,
        maximum_value = 40,
        order = "a",
    },
    -- Runtime: difficulty knobs, host-tunable mid-game.
    {
        type = "double-setting",
        setting_type = "runtime-global",
        name = "diggy-evolution-per-dig",
        default_value = 0.000002,
        minimum_value = 0,
        maximum_value = 0.001,
        order = "b-a",
    },
    {
        type = "double-setting",
        setting_type = "runtime-global",
        name = "diggy-dig-biter-chance",
        default_value = 0.1,
        minimum_value = 0,
        maximum_value = 1,
        order = "b-b",
    },
    {
        type = "double-setting",
        setting_type = "runtime-global",
        name = "diggy-dig-nest-chance",
        default_value = 0.05,
        minimum_value = 0,
        maximum_value = 1,
        order = "b-c",
    },
    {
        type = "bool-setting",
        setting_type = "runtime-global",
        name = "diggy-collapse-enabled",
        default_value = true,
        order = "c-a",
    },
    {
        type = "bool-setting",
        setting_type = "runtime-global",
        name = "diggy-collapse-broadcast",
        default_value = true,
        order = "c-b",
    },
    {
        type = "bool-setting",
        setting_type = "runtime-global",
        name = "diggy-crushed-remains",
        default_value = false,
        order = "c-c",
    },
    {
        type = "double-setting",
        setting_type = "runtime-global",
        name = "diggy-treasure-chance",
        default_value = 0.004,
        minimum_value = 0,
        maximum_value = 1,
        order = "b-e",
    },
    {
        type = "double-setting",
        setting_type = "runtime-global",
        name = "diggy-cavern-chance",
        default_value = 0.03,
        minimum_value = 0,
        maximum_value = 1,
        order = "b-f",
    },
    {
        type = "bool-setting",
        setting_type = "runtime-global",
        name = "diggy-enemy-expansion",
        default_value = false,
        order = "b-d",
    },
    {
        type = "double-setting",
        setting_type = "runtime-global",
        name = "diggy-pack-size-multiplier",
        default_value = 1.0,
        minimum_value = 0.1,
        maximum_value = 10,
        order = "b-f",
    },
    {
        type = "double-setting",
        setting_type = "runtime-global",
        name = "diggy-cavern-worm-multiplier",
        default_value = 2.0,
        minimum_value = 0,
        maximum_value = 10,
        order = "b-g",
    },
})
